apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: backend-image
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 5000
        env:
        - name: ALLOWED_ORIGIN
          value: "*"
        - name: DB_HOST
          value: "database"
        - name: DB_NAME
          value: "todo"
        - name: DB_PORT
          value: "5432"
        - name: PORT 
          value: "5000"
        -name: DB_USER
         valueFrom:
          secretKeyRef:
          name: db-secret 
          key: POSTGRES_USER
         -name: DB_PASSWORD
         valueFrom:
          secretKeyRef:
          name: db-secret 
          key: POSTGRES_PASSWORD
        

        
